/**
 * Property.js
 * Core entity of the SmartSite platform.
 *
 * Design Decisions:
 * 1. GeoJSON coordinates → enables MongoDB 2dsphere geospatial queries
 *    (nearby search, distance filtering, map-based UI)
 * 2. `aiScore` embedded → always displayed with the property, no extra query needed
 * 3. `images` as String array → stores URLs (cloud storage handles actual files)
 * 4. `amenities` as String array → supports flexible $in filtering
 * 5. `status` lifecycle enum → controls whether property appears in buyer search
 */

const mongoose = require('mongoose');

// ── Sub-schema: Location ───────────────────────────────────────────────────
/**
 * Why GeoJSON?
 * MongoDB's $geoNear, $geoWithin, and $near operators require GeoJSON format.
 * This enables: "find all properties within 5km of this point" in one query.
 * type: 'Point' is the standard GeoJSON type for a single coordinate.
 */
const locationSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: ['Point'],
      default: 'Point',
    },
    coordinates: {
      type: [Number],           // [longitude, latitude] — GeoJSON order (NOT lat, long)
      required: [true, 'Coordinates are required'],
      validate: {
        validator: function (v) {
          return (
            Array.isArray(v) &&
            v.length === 2 &&
            v[0] >= -180 && v[0] <= 180 &&   // longitude range
            v[1] >= -90  && v[1] <= 90       // latitude range
          );
        },
        message: 'Coordinates must be [longitude, latitude] with valid ranges',
      },
    },
    address: {
      type: String,
      required: [true, 'Address is required'],
      trim: true,
    },
    city: {
      type: String,
      required: [true, 'City is required'],
      trim: true,
      index: true,              // Common filter: "show properties in Mumbai"
    },
    state: {
      type: String,
      trim: true,
    },
    pincode: {
      type: String,
      trim: true,
      match: [/^\d{6}$/, 'Pincode must be 6 digits'],
    },
    country: {
      type: String,
      default: 'India',
      trim: true,
    },
  },
  { _id: false }              // Sub-schema — no need for its own _id
);

// ── Sub-schema: Specifications ─────────────────────────────────────────────
const specificationsSchema = new mongoose.Schema(
  {
    bedrooms: { type: Number, min: 0, default: 0 },
    bathrooms: { type: Number, min: 0, default: 0 },
    balconies: { type: Number, min: 0, default: 0 },
    carpetArea: { type: Number, min: 0 },     // in sq. ft.
    builtUpArea: { type: Number, min: 0 },    // in sq. ft.
    plotArea: { type: Number, min: 0 },       // for plots/villas
    floor: { type: Number },
    totalFloors: { type: Number },
    parkingSpots: { type: Number, min: 0, default: 0 },
    facing: {
      type: String,
      enum: ['North', 'South', 'East', 'West', 'North-East', 'North-West', 'South-East', 'South-West'],
    },
    furnishingStatus: {
      type: String,
      enum: ['Unfurnished', 'Semi-Furnished', 'Fully-Furnished'],
      default: 'Unfurnished',
    },
    age: { type: Number, min: 0 },            // Property age in years
  },
  { _id: false }
);

// ── Sub-schema: AI Score (generated by AI layer, stored here) ──────────────
/**
 * Why embed AI score in Property?
 * AI scores are always displayed alongside property cards.
 * Embedding avoids a $lookup to a separate collection on every listing query.
 * The score object is small and bounded — no risk of document bloat.
 */
const aiScoreSchema = new mongoose.Schema(
  {
    overall: { type: Number, min: 0, max: 100, default: null },
    locationScore: { type: Number, min: 0, max: 100, default: null },
    connectivityScore: { type: Number, min: 0, max: 100, default: null },
    amenitiesScore: { type: Number, min: 0, max: 100, default: null },
    roiPotential: { type: Number, min: 0, max: 100, default: null },
    lastScoredAt: { type: Date, default: null },
  },
  { _id: false }
);

// ── Sub-schema: Pricing Recommendation (AI-generated) ─────────────────────
const pricingRecommendationSchema = new mongoose.Schema(
  {
    suggestedMin: { type: Number, default: null },
    suggestedMax: { type: Number, default: null },
    rentSuggestion: { type: Number, default: null },
    demandProbability: { type: Number, min: 0, max: 100, default: null },   // % chance of sale
    roiEstimate: { type: Number, default: null },                            // % annual ROI
    generatedAt: { type: Date, default: null },
  },
  { _id: false }
);

// ── Main Property Schema ───────────────────────────────────────────────────
const propertySchema = new mongoose.Schema(
  {
    // ── Ownership ───────────────────────────────────────────────────────
    seller: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Property must belong to a seller'],
      index: true,          // "Get all properties listed by this seller" — very common
    },

    // ── Core Info ───────────────────────────────────────────────────────
    title: {
      type: String,
      required: [true, 'Property title is required'],
      trim: true,
      maxlength: [200, 'Title cannot exceed 200 characters'],
    },

    description: {
      type: String,
      trim: true,
      maxlength: [5000, 'Description cannot exceed 5000 characters'],
    },

    propertyType: {
      type: String,
      required: [true, 'Property type is required'],
      enum: {
        values: ['Apartment', 'Villa', 'Plot', 'Commercial', 'Office', 'Shop', 'Farmhouse', 'Studio'],
        message: 'Invalid property type',
      },
      index: true,          // Frequently filtered: "show only Apartments"
    },

    listingType: {
      type: String,
      required: [true, 'Listing type is required'],
      enum: ['Sale', 'Rent', 'Lease'],
      index: true,
    },

    // ── Pricing ─────────────────────────────────────────────────────────
    price: {
      type: Number,
      required: [true, 'Price is required'],
      min: [0, 'Price cannot be negative'],
      index: true,          // Range queries: price >= X AND price <= Y
    },

    pricePerSqFt: {
      type: Number,
      min: 0,
    },

    isPriceNegotiable: {
      type: Boolean,
      default: false,
    },

    // ── Location ────────────────────────────────────────────────────────
    location: {
      type: locationSchema,
      required: [true, 'Location is required'],
    },

    // ── Specifications ───────────────────────────────────────────────────
    specifications: {
      type: specificationsSchema,
      default: {},
    },

    // ── Amenities ────────────────────────────────────────────────────────
    /**
     * Stored as an array of strings for maximum flexibility.
     * Queried with: { amenities: { $in: ['Gym', 'Swimming Pool'] } }
     * New amenities can be added without schema migration.
     */
    amenities: {
      type: [String],
      default: [],
      enum: {
        values: [
          'Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security',
          'Power Backup', 'Garden', 'Clubhouse', 'CCTV', 'Intercom',
          'Rainwater Harvesting', 'Solar Panels', 'Children Play Area',
          'Jogging Track', 'Tennis Court', 'Basketball Court',
          'Gas Pipeline', 'Water Storage', 'Maintenance Staff',
        ],
        message: '{VALUE} is not a supported amenity',
      },
    },

    // ── Media ────────────────────────────────────────────────────────────
    images: {
      type: [String],       // Array of image URLs from cloud storage
      default: [],
      validate: {
        validator: (v) => v.length <= 20,
        message: 'A property can have at most 20 images',
      },
    },

    // ── Status Lifecycle ─────────────────────────────────────────────────
    /**
     * Controls visibility in buyer search:
     * - 'draft'              → seller is still filling details, hidden from buyers
     * - 'available'          → visible in search results
     * - 'under_negotiation'  → offer received, temporarily hidden
     * - 'sold'               → permanently removed from active search
     */
    status: {
      type: String,
      enum: ['draft', 'available', 'under_negotiation', 'sold'],
      default: 'draft',
      index: true,
    },

    // ── AI Intelligence ───────────────────────────────────────────────────
    aiScore: {
      type: aiScoreSchema,
      default: {},
    },

    pricingRecommendation: {
      type: pricingRecommendationSchema,
      default: {},
    },

    // ── Engagement Counters (lightweight, updated in-place) ──────────────
    views: {
      type: Number,
      default: 0,
    },

    saves: {
      type: Number,
      default: 0,
    },

    inquiries: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ── Indexes ────────────────────────────────────────────────────────────────

/**
 * 2dsphere index on location.coordinates:
 * Required for all MongoDB geospatial operators ($geoNear, $geoWithin, $near).
 * Without this, geospatial queries will fail with an error.
 */
propertySchema.index({ 'location.coordinates': '2dsphere' });

/**
 * Text index on title + description:
 * Enables full-text search: db.properties.find({ $text: { $search: "3BHK metro" } })
 * Weights control ranking — title matches rank higher than description matches.
 */
propertySchema.index(
  { title: 'text', description: 'text' },
  { weights: { title: 10, description: 3 }, name: 'PropertyTextIndex' }
);

/**
 * Compound index for the most common buyer search filter:
 * "Show available apartments for sale, priced between X and Y"
 * Covers: status + listingType + propertyType + price
 */
propertySchema.index({ status: 1, listingType: 1, propertyType: 1, price: 1 });

/**
 * Seller's dashboard query: "Show all my listings"
 * Covered by the seller + status compound index.
 */
propertySchema.index({ seller: 1, status: 1 });

/**
 * City-based filtering — very common in Indian real estate context.
 */
propertySchema.index({ 'location.city': 1, status: 1, price: 1 });

/**
 * AI score sorting — for "top rated properties" view.
 */
propertySchema.index({ 'aiScore.overall': -1 });

// ── Virtual: formatted price ──────────────────────────────────────────────
propertySchema.virtual('formattedPrice').get(function () {
  if (this.price >= 10000000) return `₹${(this.price / 10000000).toFixed(2)} Cr`;
  if (this.price >= 100000) return `₹${(this.price / 100000).toFixed(2)} L`;
  return `₹${this.price.toLocaleString('en-IN')}`;
});

const Property = mongoose.model('Property', propertySchema);

module.exports = Property;
